# Object Coordinates
#         P_4                                 P_3
#          +----------------------------+
#          |                                       |
#          |                                       |
#          |               (0,0)               |
#          |                                       |
#          |                                       |
#          +----------------------------+
#          P_1                               P_2
# 
object_coordinates:
  [
    [-0.20, -0.20, 0.20, -0.20],
    [0.20, -0.20, 0.20, 0.20],
    [0.20, 0.20, -0.20, 0.20],
    [-0.20, 0.20, -0.20, -0.20],
  ]

# Object Scale (Need to be the same as state in the object urdf file)
scale_x: 1.0
scale_y: 1.0
